name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.14.3"

      - name: Build and Deploy Sphinx Documentation
        run: |
          uv run \
            --with sphinx \
            --with sphinx-rtd-theme \
            --with src/bim \
            --with src/dot \
            --with src/fctracker \
            --with src/hello_world \
            --with src/muc \
            --with src/outlookctl \
            --with src/pinger \
            --with src/readerctl \
            --with src/zseq \
            sphinx-build -b html ./docs/source ./docs/build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./docs/build/html"
